### ISSUE TITLE
How to: equal height columns with background-color

### ISSUE THREAD

**Issue by mmjaeger** [Objectway/super-gigi#1]
Hello
I'm looking into your super-gigi mixins and I was wondering how you would go about creating some equal height columns each with a different background color.

**Comment by MakhBeth** [comment]
Something like that?
http://codepen.io/MakhBeth/pen/aZzdYy?editors=1100

**Comment by mmjaeger** [comment]
Thank you for replying - yes, something like that BUT with a gutter

On Tue, May 31, 2016 at 8:51 AM, Davide Di Pumpo <notifications@github.com>
wrote:

> Something like that?
> http://codepen.io/MakhBeth/pen/aZzdYy?editors=1100
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/1#issuecomment-222732491>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lCEG9GAlUeyJoUFHl-TmkpPNXInnks5qHFkNgaJpZM4IqoZw>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by MakhBeth** [comment]
Yeah, to do that you have to do something like that: http://codepen.io/MakhBeth/pen/aZzdYy (I've updated the old example, changing a little the dom using another element).
