### ISSUE TITLE
Disable box-sizing prop in grid if already globally set

### ISSUE THREAD

**Issue by ekfuhrmann** [Objectway/super-gigi#13]
It would be great if there was an option we could set to remove the `box-sizing` property from the grid in the case we have already defined it globally. If you'd like I could make a PR?

**Comment by MakhBeth** [comment]
No, there is not a specific option for that.
But you can use `@include grid-column($global: false)` to avoid to generate
box-sizing. But with that you will loose also the rules: `display: flex`
and `flex-direction: column`. That rules are not needed in every case, but
have a try in your case.

On the repetition:
If you use gzip, css repetitions are not an issue at all. Every repetition
is compressed, so there is not bytes difference.

If you don't have gzip, give a try to the `use-dry` option. You can find it
in the README. It will avoid the repetitions for you
Il giorno lun 14 ago 2017 alle 18:00 Eric Fuhrmann <notifications@github.com>
ha scritto:

**Comment by ekfuhrmann** [comment]
Interesting, I didn't realize that about gzip. Well that definitely is a good solution for myself, so I will close this issue.

That said, I did create a PR for adding another setting that would disable this as well. Perhaps it's worth keeping in case someone does not wish to compile with gzip?

Regardless feel free to decline my PR if you feel that gzip is a suitable solution.

**Comment by MakhBeth** [comment]
The PR is a good idea, I will leave that here, waiting if someone has
something to say. (And I'm in vacation, so I will open a real pc in weeks
:D)

Cheers
Il giorno lun 14 ago 2017 alle 19:05 Eric Fuhrmann <notifications@github.com>
ha scritto:
