### ISSUE TITLE
Gutter: option to either use margin or padding

### ISSUE THREAD

**Issue by mmjaeger** [Objectway/super-gigi#2]
Hello
It would be nice to have an option to either use padding or margin as gutter

**Comment by MakhBeth** [comment]
I've thought a lot about that option. I'm not sure if it's useful, I can add that in experimental, in the next release, maybe I underestimated that :D

**Comment by mmjaeger** [comment]
I'd look forward to that - thanks again.

On Thu, Jun 2, 2016 at 4:43 AM, Davide Di Pumpo <notifications@github.com>
wrote:

> I've thought a lot about that option. I'm not sure if it's useful, I can
> add that in experimental, in the next release, maybe I underestimated that
> :D
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-223267902>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lPlqQPy1iGSna8kDgIba6lxwQ6LTks5qHsHxgaJpZM4IrEAA>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
Was wondering whether you were able to put some more thoughts into this - the main advantage of using margin as gutter would be that one would be able to have background-color on column items, cells without any further html markup needed.

**Comment by MakhBeth** [comment]
I'm already on that task, but I want to rewrite the function that returns dimensions also. 
Probably at the end of the month it will be here in experimental option.

**Comment by mmjaeger** [comment]
Sounds great - looking forward to it

On Sat, Jun 18, 2016 at 2:35 AM, Davide Di Pumpo <notifications@github.com>
wrote:

> I'm already on that task, but I want to rewrite the function that returns
> dimensions also.
> Probably at the end of the month it will be here in experimental option.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-226932524>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lA6vFRmBsZ0S9edfxg-H80FLgZRKks5qM7vqgaJpZM4IrEAA>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by MakhBeth** [comment]
Ok, the new feature is here: http://codepen.io/MakhBeth/pen/wWoKOb?editors=1100

You can set it globally via `$sg-use-margin` option or locally via the `$margin` parameter of the `grid-column` mixin. I wrote something about that in the docs.

Thanks for the hint.

**Comment by mmjaeger** [comment]
Sounds great - I will certainly give it a shot - Thanks for your work

On Tue, Jun 21, 2016 at 8:28 AM, Davide Di Pumpo <notifications@github.com>
wrote:

> Ok, the new feature is here:
> http://codepen.io/MakhBeth/pen/wWoKOb?editors=1100
>
> You can set it globally via $sg-use-margin option or locally via the
> $margin parameter of the grid-column mixin. I wrote something about that
> in the docs.
>
> Thanks for the hint.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-227477002>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lPFaY5WW9rimWxidVC-bKoBnL7K4ks5qOAMhgaJpZM4IrEAA>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
Maybe it would be helpful if one could pass some $padding in case margin is
used as gutter - I see that you set left and right padding if not collapsed
- in case I'd like to give the column a background, I think top and bottom
padding also need to be set?



On Tue, Jun 21, 2016 at 8:52 AM, Marco M. Jaeger <mmjaeger@gmail.com> wrote:

> Sounds great - I will certainly give it a shot - Thanks for your work
>
> On Tue, Jun 21, 2016 at 8:28 AM, Davide Di Pumpo <notifications@github.com
> > wrote:
>
>> Ok, the new feature is here:
>> http://codepen.io/MakhBeth/pen/wWoKOb?editors=1100
>>
>> You can set it globally via $sg-use-margin option or locally via the
>> $margin parameter of the grid-column mixin. I wrote something about that
>> in the docs.
>>
>> Thanks for the hint.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-227477002>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABe4lPFaY5WW9rimWxidVC-bKoBnL7K4ks5qOAMhgaJpZM4IrEAA>
>> .
>>
>
>
>
> --
> Marco M. Jaeger
> http://net4visions.com
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by MakhBeth** [comment]
Yeah, it's a common case, but I don't want to add more features in the column mixin. It's still possible to use css after the mixin declaration, for example add `padding-top: ($column-gutter / 2)` after the grid-column mixin it's a clearer way than add another option inside the mixin.  It's the same things about the flex alignment. I prefer to declare `align-items: center` after the mixin declaration instead of add an option `$center: true` inside the mixin.

For the margins was different because if you declare margins gutter, you have to change the width of the object, considering the new dimensions added to the horizontal box-model of the object.

**Comment by MakhBeth** [comment]
Oh, I forgot. Thanks again for the hints. Please when you'll try it, tell me if everything work as aspected.

**Comment by mmjaeger** [comment]
Hello
Quick question - did you try to use margin and push - looking at the
calculation mixin I think it would return  the percentage minus the margin
gutter and I think it should only return the full with - maybe I'm wrong

On Tue, Jun 21, 2016 at 9:43 AM, Davide Di Pumpo <notifications@github.com>
wrote:

> Oh, I forgot. Thanks again for the hints. Please when you'll try it, tell
> me if everything work as aspected.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-227499271>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lA2S53Ji-XkVF6gps7LTvbJBT-Gyks5qOBSvgaJpZM4IrEAA>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by MakhBeth** [comment]
There weren't issues with push and margins, because push use `left` property. 
The issue you suggested was here with `$offset` unfortunately. Nice found :D 

I fixed that with the `1.12.5` version. 
Thanks

**Comment by mmjaeger** [comment]
Hello Davide
Let me make a suggestion: when setting the gutter either margin or padding,
I think you should do padding-right and padding-left or margin-right and
margin-left instead of padding: 0 gutter or margin: 0 gutter - I'd a hard
time to set a vertical margin to give the columns some space - what do you
think

On Sat, Jun 25, 2016 at 2:59 PM, Davide Di Pumpo <notifications@github.com>
wrote:

> There weren't issues with push and margins, because push use left
> property.
> The issue you suggested was here with $offset unfortunately. Nice found
> :D
>
> I fixed that with the 1.12.5 version.
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-228572490>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lCXTmOq_EXW0v6zykqVVS083PCEeks5qPaSsgaJpZM4IrEAA>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
Allow me another question: I see you're using width instead of flex-basis
to define an element's / column's dimension - why is that - any advantage
of using with instead of flex-basis.

Another think you may want to consider, if I set $collapsed to true, the
padding is removed but not the margin - I think if margin is used as
gutter, the margin should be removed.

On Sun, Jun 26, 2016 at 9:15 AM, Marco M. Jaeger <mmjaeger@gmail.com> wrote:

> Hello Davide
> Let me make a suggestion: when setting the gutter either margin or
> padding, I think you should do padding-right and padding-left or
> margin-right and margin-left instead of padding: 0 gutter or margin: 0
> gutter - I'd a hard time to set a vertical margin to give the columns some
> space - what do you think
>
> On Sat, Jun 25, 2016 at 2:59 PM, Davide Di Pumpo <notifications@github.com
> > wrote:
>
>> There weren't issues with push and margins, because push use left
>> property.
>> The issue you suggested was here with $offset unfortunately. Nice found
>> :D
>>
>> I fixed that with the 1.12.5 version.
>> Thanks
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Objectway/super-gigi/issues/2#issuecomment-228572490>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABe4lCXTmOq_EXW0v6zykqVVS083PCEeks5qPaSsgaJpZM4IrEAA>
>> .
>>
>
>
>
> --
> Marco M. Jaeger
> http://net4visions.com
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by MakhBeth** [comment]
About padding/margin. Yeah, define only padding/margin-left/right should be clearer. It comes to my way of write CSS, and Sass (Mixins before single properties). 
Grid mixins before, after overwrite properties. But hindsight define that specifically is better. The problem now is to change that on the way. It could be a breaking change for others. But in the next main release I will totally change that.

About width instead of flex-basis. For browsers render dimensions based on flex-basis is more difficult. So using width directly is a little optimization to reduce browsers render time. The result is the same, so I preferred to optimize. 
Another reason is to have table or float fallback, without add a lot of useless code.

About collapse: Uhm, yeah, I think that is a good Idea that IF you have global margin, collapse will remove that. I will add that in the next patch version.
