### ISSUE TITLE
holy grail layout

### ISSUE THREAD

**Issue by mmjaeger** [Objectway/super-gigi#4]
hello
let's say I have the following html layout:
aside
main
aside
is it possible to have the two asides at e.g. 20rem or 300px and the main container would have the remaining space - what I'm basically after is having the sidebar at a fixed width and the main container flexible?

thanks

**Comment by MakhBeth** [comment]
You can easily override super-gigi behaviors in cascade: 
http://codepen.io/MakhBeth/pen/JKKbRY
